[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# EntryPoint V0.8 is built with minimum version of cancun
solc = "0.8.28"
evm_version = 'cancun'

# EntryPoint V0.6 and v0.7 *needs* to be built with evm_version set to london
#solc = "0.8.26"
#evm_version = 'london'

optimizer = true
optimizer_runs = 1000000
gas_limit = "18446744073709551615"
ast = true

[profile.default.optimizer_details]
yul = false

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
