[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"

optimizer = true
optimizer_runs = 1000000
ast = true

[default.optimizer_details]
yul = false

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true